InputRequestEnum = {
    'INPUT_REQUEST_MOUSE_MOVE': 1,
    'INPUT_REQUEST_MOUSE_LEFT_CLICK': 2,
    'INPUT_REQUEST_MOUSE_RIGHT_DOWN': 3,
    'INPUT_REQUEST_MOUSE_RIGHT_CLICK': 4,
    'INPUT_REQUEST_MOUSE_AREA': 5,
    'INPUT_REQUEST_MOUSE_AREA_ADDITIVE': 6,
    'INPUT_REQUEST_SELL_AT_POSITION': 7,
    'INPUT_REQUEST_SELECT_AT_POSITION': 8,
    'INPUT_REQUEST_COMMAND_AT_POSITION': 9,
    'INPUT_REQUEST_SPECIAL_KEYS': 10,
}

StructureRequestEnum = {
    'INPUT_STRUCTURE_REPAIR_START': 1,
    'INPUT_STRUCTURE_REPAIR': 2,
    'INPUT_STRUCTURE_SELL_START': 3,
    'INPUT_STRUCTURE_SELL': 4,
    'INPUT_STRUCTURE_CANCEL': 5,
}

UnitRequestEnum = {
    'INPUT_UNIT_SCATTER': 1,
    'INPUT_UNIT_SELECT_NEXT': 2,
    'INPUT_UNIT_SELECT_PREVIOUS': 3,
    'INPUT_UNIT_GUARD_MODE': 4,
    'INPUT_UNIT_STOP': 5,
}

SidebarRequestEnum = {
    'SIDEBAR_REQUEST_START_CONSTRUCTION': 0,
    'SIDEBAR_REQUEST_HOLD_CONSTRUCTION': 1,
    'SIDEBAR_REQUEST_CANCEL_CONSTRUCTION': 2,
    'SIDEBAR_REQUEST_START_PLACEMENT': 3,
    'SIDEBAR_REQUEST_PLACE': 4,
    'SIDEBAR_CANCEL_PLACE': 5,
}

SuperWeaponRequestEnum = {'SUPERWEAPON_REQUEST_PLACE_SUPER_WEAPON': 0}

ControlGroupRequestEnum = {
    'CONTROL_GROUP_REQUEST_CREATE': 0,
    'CONTROL_GROUP_REQUEST_TOGGLE': 1,
    'CONTROL_GROUP_REQUEST_ADDITIVE_SELECTION': 2,
}

BeaconRequestEnum = {
    'INPUT_BEACON_PLACE': 1,
}
