name: test
on: push
defaults:
  run:
    shell: cmd
jobs:
  test_py_lib:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: python -m pip install .
    - name: Test import
      run: |
        cd \
        python -m cnc_ai.TIBERIANDAWN.run -h
  code:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: python -m pip install black pylint
    - name: Formatting
      run: black --check --line-length=99 --skip-string-normalization --target-version=py310 cnc_ai
    - name: Lint
      run: pylint --recursive y --enable-all-extensions --fail-under 10 -d C0114,C0115,C0116,E0401,R0903 cnc_ai
  build_wrapper:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3
    - name: Build
      run: |
        cd DllWrapper
        cmake -A Win32 .
        msbuild /p:Configuration=Release /p:Platform=Win32 DllWrapper.sln
        msbuild /p:Configuration=Debug /p:Platform=Win32 DllWrapper.sln
    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: bin
        path: |
          DllWrapper/Release/*.exe
          DllWrapper/Debug/*.*
