name: test
on: push
defaults:
  run:
    shell: cmd
jobs:
  test_py_lib:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: python -m pip install .
    - name: Test import
      run: |
        cd \
        python -m cnc_ai.background_model -h
  build_null_callback:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Build
      run: |
        cd null_callback
        cmake -G "Visual Studio 16 2019" -A Win32 .
        msbuild /p:Configuration=Release /p:Platform=Win32 null_callback.sln
    - name: Upload DLLs
      uses: actions/upload-artifact@v2
      with:
        name: bin
        path: null_callback/Release/*.dll
