name: test
on: push
defaults:
  run:
    shell: cmd
jobs:
  test_py_lib:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: python -m pip install .
    - name: Test import
      run: |
        cd \
        python -m cnc_ai.background_model -h
