name: test
on: push
defaults:
  run:
    shell: cmd
jobs:
  test_py_lib:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: python -m pip install .
    - name: Test import
      run: |
        cd \
        python -m cnc_ai.TIBERIANDAWN.run -h
  build_wrapper:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Build
      run: |
        cd DllWrapper
        cmake -A Win32 .
        msbuild /p:Configuration=Release /p:Platform=Win32 DllWrapper.sln
        msbuild /p:Configuration=Debug /p:Platform=Win32 DllWrapper.sln
    - name: Upload files
      uses: actions/upload-artifact@v2
      with:
        name: bin
        path: |
          DllWrapper/Release/*.exe
          DllWrapper/Debug/*.*
